services:
  cuda-dev-base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NVIM_CONFIG_REPO=${NVIM_CONFIG_REPO:-https://github.com/spagdoon0411/nvim.git}
        - NVIM_CONFIG_BRANCH=main
    image: nvidia/cuda:12.9.0-cudnn-runtime-ubuntu24.04

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    volumes:
      - .:/workspace
    working_dir: /workspace

    tty: true
    stdin_open: true
    user: dev

  cuda-dev:
    container_name: cuda-dev-container
    extends:
      service: cuda-dev-base
      runtime: nvidia

  cuda-dev-gpu:
    container_name: cuda-dev-gpu-container
    extends:
      service: cuda-dev-base
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
